spring:
  datasource:
    url: jdbc:h2:file:./db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true

jwt:
  secret: secret